plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "spec/fixtures/**/*"

Layout/LineLength:
  Max: 150

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: true

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false