name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby 4.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.0

      - name: Install dependencies
        run: |
          bundle config set frozen true
          bundle install

      - name: Debug versions
        run: |
          ruby -v
          bundle exec rubocop -V

      - name: Run linter
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby 4.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.0

      - name: Install dependencies
        run: |
          bundle config set frozen true
          bundle install

      - name: Run tests
        run: bundle exec rspec